export const getLanguage = (extensions) => {
  const languages = {
    bat: "bat",
    c: "c",
    cpp: "cpp",
    cs: "csharp",
    css: "css",
    dockerfile: "dockerfile",
    m: "objective-c",
    h: "objective-c",
    mm: "objective-cpp",
    go: "go",
    html: "html",
    java: "java",
    js: "javascript",
    jsx: "javascriptreact",
    json: "json",
    kt: "kotlin",
    md: "markdown",
    perl: "perl",
    php: "php",
    py: "python",
    rb: "ruby",
    rs: "rust",
    scss: "scss",
    sql: "sql",
    vue: "vue",
    sh: "shellscript",
    swift: "swift",
    ts: "typescript",
    tsx: "typescriptreact",
    xml: "xml",
    yaml: "yaml",
  };
  return languages[extensions] || "plaintext";
};
